name: "Test"

on:
  push:
    branches:
      - "main"
      - "dev"

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: The only step
        uses: "./action.yaml"
        with:
          library: "node:fs"
          imports: "readFileSync"
